<?php
// Declare Variables 
         $hostname='localhost';
	 $usernamehost='diavatly';
	 $passwordhost='cntt2019';
	 $databasename='diavatly_db';
         $php ="php";
	 $java="java";
         $css="css";
         $html="html";
         $upload="upload"; 	 
// Connect to MySQL

$link =mysql_connect($hostname,$usernamehost,$passwordhost) or die("Can't connect to server");

// Using Database
		
mysql_select_db($databasename,$link) or die("Can't select database");
//mysql_query("SET NAMES 'utf8'", $link);

// Create array chucdanh

/*$cdarray = array (
	       "Giám đốc XN",
	       "PGD về công nghệ",
	       "Chánh kỹ sư",
	       "Chánh kế toán",
	       "Xưởng trưởng",
	       "Trưởng trung tâm PTXLTL",
	       "Trưởng phòng KTKH",
	       "đội trưởng",
	       "Trưởng phòng KTSX",
	       "Phó phòng KTSX",
	       "Xưởng Phó",
	       "Đội phó",
	       "Phó Trung tâm PTXLTL",
	       "CVC Cán Bộ",
	       "CVC Bậc 7",
	       "CVC Bậc 6",
	       "CVC Bậc 5",
	       "CVC Bậc 4",
	       "CVC Bậc 3",
	       "CVC Bậc 2",
	       "CVC Bậc 1",
	       "Đốc công thử vỉa",
	       "KS bậc 9",
	       "KS bậc 8",
	       "KS bậc 7",
	       "KS bậc 6",
	       "KS bậc 5",
	       "KS bậc 4",
	       "KS bậc 3",
	       "KS bậc 2",
	       "KS bậc 1",
	       "thợ bậc 6",
	       "thợ bậc 5",
	       "thợ bậc 4",
	       "thợ bậc 3",
	       "thợ bậc 2",
	       "thợ bậc 1",
	       "KTV bậc 10",
	       "KTV bậc 9",
	       "KTV bậc 8",
	       "KTV bậc 7",
	       "KTV bậc 6",
	       "KTV bậc 5",
	       "KTV bậc 4",
	       "KTV bậc 3",
	       "KTV bậc 2",
	       "KTV bậc 1",
	       "CN bậc 6",
	       "CN bậc 5",
	       "CN bậc 4",
	       "CN bậc 3",
	       "CN bậc 2",
	       "CN bậc 1",
	       "Thủ Qũy",
	       "Thư ký đánh máy",
	       "Nhân viên hành chính",
	       "Chủ nhiệm HC-QT",
	       "Chủ nhiệm lưu trữ",
	       "Tạp vụ bậc 6",
	       "Tạp vụ bậc 5",
	       "Tạp vụ bậc 4",
	       "Tạp vụ bậc 3",
	       "Tạp vụ bậc 2",
	       "Tạp vụ bậc 1",
	       "Chức danh khác"
       );
// Create array donvi
$dvarray = array (
               "Ban lãnh đạo",
	       "Bộ phận trực thuộc lãnh đạo",
	       "Phòng kỹ thuật sản xuất",
	       "Phòng kinh tế kỹ thuật",
	       "Phòng kế toán",
	       "Đội Carota tổng hợp",
	       "Đội công nghệ cao",
	       "Đội Carota khí",
	       "Trung tâm phân tích và xử lý TL",
	       "Đội thử vỉa",
	       "Xưởng sửa chữa và chuẩn chỉnh máy ĐVL",
	       "Xưởng sửa chữa thiết bị chuyên dụng",
	       "Đội kiểm tra khai thác"
	);
 */
// Create array trinhdochuyenmon
$hvarray = array (
     	       "TSKH",
	       "TS",
	       "ThS",
	       "Đại học",
	       "Cao đẳng",
	       "Trung cấp",
	       "Nhân viên",
	       "Công Nhân",
	       "Lao động phổ thông"
	);
// Create array ngoaingu
$nnarray = array (
	       "Anh",
	       "Nga",
	       "Pháp",
	       "Đức",
	       "Nhật",
	       "Trungquốc",
	       "Hàn",
	       "Khác",
	       "Không"
	);
// Create array bangcap
$bcarray = array (
               "A",
	       "B",
	       "C",
	       "D",
	       "TOEIC",
	       "TOEFL",
	       "IELTS",
	       "Bằngkhác",
	       "Không"
	);
// Create array country
$carray = array (
"Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Arabia, Saudi",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahrain",
"Bangladesh",
"Belarus",
"Belgium",
"Bolivia",
"Bosnia and Herzegovina",
"Brazil",
"Bulgaria",
"Cambodia",
"Cameroon",
"Canada",
"Chile",
"China",
"Colombia",
"Costa Rica",
"Croatia",
"Cuba",
"Czech Republic",
"Denmark",
"Dominica",
"Ecuador",
"Egypt",
"El Salvador",
"Finland",
"France",
"Germany",
"Ghana",
"Greece",
"Hong Kong, (China)",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Korea North ",
"Korea South",
"Kuwait",
"Lao ",
"Luxembourg",
"Macao, (China)",
"Malaysia",
"Mexico",
"Monaco",
"Morocco",
"Myanmar",
"Nigeria",
"Norway",
"Oman",
"Pakistan",
"Panama",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russia",
"Saudi Arabia",
"Senegal",
"Serbia ",
"Singapore",
"Slovakia",
"Slovenia",
"South Africa",
"Spain",
"Sri Lanka ",
"Sweden",
"Switzerland",
"Taiwan",
"Thailand",
"Turkey",
"Turkmenistan",
"Ukraine",
"UAE",
"United Kingdom",
"United States",
"Uruguay",
"Uzbekistan",
"Venezuela",
"Viet Nam",
"Yemen",
"Zambia",
"Zimbabwe"
	);
$cnarray = array (
"Afghanistan",
"Albania",
"Algeria",
"Angola",
"Arabia, Saudi",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahrain",
"Bangladesh",
"Belarus",
"Belgium",
"Bolivia",
"Bosnia and Herzegovina",
"Brazil",
"Bulgaria",
"Cambodia",
"Cameroon",
"Canada",
"Chile",
"China",
"Colombia",
"Costa Rica",
"Croatia",
"Cuba",
"Czech Republic",
"Denmark",
"Dominica",
"Ecuador",
"Egypt",
"El Salvador",
"Finland",
"France",
"Germany",
"Ghana",
"Greece",
"Hong Kong, (China)",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Korea North ",
"Korea South",
"Kuwait",
"Lao ",
"Luxembourg",
"Macao, (China)",
"Malaysia",
"Mexico",
"Monaco",
"Morocco",
"Myanmar",
"Nigeria",
"Norway",
"Oman",
"Pakistan",
"Panama",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russia",
"Saudi Arabia",
"Serbia ",
"Singapore",
"Slovakia",
"Slovenia",
"South Africa",
"Spain",
"Sri Lanka ",
"Sweden",
"Switzerland",
"Taiwan",
"Thailand",
"Turkey",
"Turkmenistan",
"UAE",
"Ukraine",
"United Kingdom",
"United States",
"Uruguay",
"Uzbekistan",
"Venezuela",
	);

?>
